### ISSUE TITLE
There is no way to keep an InputStream alive for the whole life of the Process

### ISSUE THREAD

**Issue by frayien** [fleipold/jproc#24]
In my current project I start a long running process and I need to send it data through the standard input sparingly.

However there seems to be no way to do that as you stop reading the InputStream and close the Process's underlying OutputStream as soon as the initial reading is completed.

**Comment by fleipold** [comment]
@frayien thank you for your feedback. Currently `jproc` is targeting non-interactive use cases, i.e. it handles the complete feeding of the input into the process and collecting the output. This allows for a simple API.

What does your use case look like?

Could you sketch out in (pseudo) code how you would like to invoke `jproc`?

**Comment by frayien** [comment]
@fleipold My application starts a game server, and needs to keep the input alive to send commands the user may want to send while the server is running.

I tried to call `jproc` like this :
```java
process_builder = new ProcBuilder("java")
			.withArgs(args.toString().split(" "))
			.withWorkingDirectory(serv)
			.withNoTimeout()
			.withOutputStream(output)
			.withErrorStream(output)
			.withInputStream(input);
```
Where `input` is a custom InputStream.
I expected it not to stop reading from the stream, waiting for new data to arrive.
I did it this way because I tried what made the most sense with what methods ProcBuilder have. 
If you ever want to add this possibility to `jproc`, I feel like there is a cleaner way to do that. 
But of course I dont expect you to rework `jproc` for my highly specific use case, but I though I may be interesting to discuss.

**Comment by fleipold** [comment]
Hi @frayien,

I believe that your use case actually works quite well with Java's [ProcessBuilder](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html) interface. By default it connects pipes for input and output and you can just read from it's output stream and write to it's input stream.

JProc goes a long way to invert this, so that input is fed into process from an input stream or (String or ByteArray) and the output is consumed automatically. I am not sure if the rest of JProc is worth the hassle.

What you could try is to pass in a pipe as input. It should be read while it's not closed, along these lines:
```
        final PipedOutputStream outputForStdIn = new PipedOutputStream();
        final PipedInputStream input = new PipedInputStream(outputForStdIn);
        final ByteArrayOutputStream outputProper = new ByteArrayOutputStream();

        final Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                new ProcBuilder("cat")
                    .withInputStream(input)
                    .withOutputStream(outputProper)
                    .run();
                System.out.println("DONE");
            }
        });

        thread.start();

        PrintWriter writer = new PrintWriter(new OutputStreamWriter(outputForStdIn, StandardCharsets.UTF_8));
        writer.println("Hello");
        writer.flush();

        thread.sleep(100);
        assertEquals("Hello\n", outputProper.toString("utf-8"));

        writer.close();

        thread.interrupt();
``` 

However this doesn't currently work properly, because the output doesn't get flushed aggressively enough (Would probably have to flush after StreamCopyRunner.java:32: `out.flush()`.

**Comment by frayien** [comment]
Hi @fleipold,

First thanks you for taking time to answer me on something that is less and less related to your library, I very appreciate it. 

As you said, JProc goes a long way to invert how Java's Process work, and I am kind of trying to revert it back so... not the best.
Looking at it JProc and Java's Process have an opposite approach on how to handle a process, and my needs are somewhere in the middle of it.

Java's process :
- Process is asynchronous, it lives independently of the main application.
- Input is written on the fly
- Output must be read on the fly

JProc :
- Proc is synchronous, the process is dependent on the main application to exist.
- Input is written in one go at the start
- Output is read when the process has ended

What I want is JProc's synchronicity, Java's Process Input management and either JProc's or Java's Output management (both of them work but JProc's leads to a simpler code on my end)

What I did is using Java's Process, while being careful to kill it if the main program is ended and having a specific thread to actively read it's output and store it in a circular buffer.
I also added :
```java
@Override
public void finalize()
{
    if(process != null) process.destroyForcibly();
}
```
which I have no idea if it has any effect as I am not familiar enough with how Java handle finalize, but meh, why not.

It is temporary, I think what I will end up doing I making my own class to encapsulate Java's Process, taking inspiration from JProc, maybe starting from a fork of JProc I dont know.

**Comment by fleipold** [comment]
@frayien I still believe going with the Java Process is the right way for you. It is important to note that there are no guarantees, that finalize is being called. If your program terminates properly, you can always do it at the end of the main method. 

If your main method exits before the program terminates, because all the real work is done in threads you might have to join them in the main method to wait until they have terminated.

If your process gets killed (-9) there is no way to do anything.

If your process gets terminated with TERM signal, you could register a signal handler, that does some cleanup.

Thanks a lot for your interesting observations. I'll close this ticket, as it would be very hard to add an asynchronous API to the current form of jproc (once there was an incarnation of this library that had a method like `runAsync`, but I refactored it to make the non-interactive use case more straightforward).

**Comment by frayien** [comment]
@fleipold Thank you for your help ! What I ended up doing was writing my own class to encapsulate Java's Process, in a kind of similar idea of what you did with JProc but specifically adapted for my needs.

I dropped the idea about finalize, I just used process.waitFor() with a catch for InterruptedException ; kind of what you did in JProc.java:143.

I can provide my code if you are curious, but I dont think it is highly relevant.
