### ISSUE TITLE
Process termination is not guaranted on Interruption

### ISSUE THREAD

**Issue by frayien** [fleipold/jproc#25]
I need to ensure the running program is killed if the Thread the Proc is called in is Interrupted. I expected it to be the case as the call is blocking, but it is not.

**Comment by fleipold** [comment]
Good catch. Thank you.

To me it looks like the culprit is somewhere near these locations:

1. https://github.com/fleipold/jproc/blob/6b50a5491373a5e33d823255a5d84bae9337f39f/src/main/java/org/buildobjects/process/Proc.java#L114

2. https://github.com/fleipold/jproc/blob/6b50a5491373a5e33d823255a5d84bae9337f39f/src/main/java/org/buildobjects/process/Proc.java#L146

I'll need to write a test and fix it in the right place, which I wont be able to look into until the weekend.

**Comment by fleipold** [comment]
Fixed in 2.6.1.
