### ISSUE TITLE
Env vars handling

### ISSUE THREAD

**Issue by sebthom** [fleipold/jproc#28]
I am trying to migrate some code from java.lang.ProcessBuilder to ProcBuilder and have a few questions regarding env var handling.

1. How can I control whether or not environment variables are inherited from the parent process?
   In java.lang.ProcessBuilder the default is to inherit all env vars and I can prevent this with a single call to:
`processBuilder.environment().clear()`

2. How can I set multiple env vars at once. Having to iterate over all vars and using the `withVar(key, value)` builder method defeats the purpose of fluent builder methods. So I am looking for a `withVars(Map<String,String>)` builder method or similar.

Thanks in advance!

**Comment by fleipold** [comment]
@sebthom thanks for your feedback!

Re 1: I overlooked this use case. It needs to be added. Probably something along the lines of `procBuilder.clearEnvironment()`.

Re 2: I didn't have this use case (as most of the work pre-dates closures and streams as well as `Map.of(Pair<K,V>…)`. It makes total sense to add `withVars(Map<String, String>)`.

I am happy to add these things. I won't probably get to it until the mid of the week. Otherwise I am also happy to accept pull requests ;-).

**Comment by systemhalted** [comment]
@fleipold I am working on (2) as I need it for my work. Hope to get a PR out soon.

**Comment by fleipold** [comment]
Thanks to @systemhalted 's PR a fix for the second issue is on its way to maven central and should show up as v2.7.0 on maven central soon. Re 1 @sebthom would adding a `clearEnvironment` method sound reasonable. It would be applied before any of the vars have been set.

**Comment by sebthom** [comment]
That sounds reasonable!

**Comment by fleipold** [comment]
Erledigt. 2.8.0 is on its way out to maven central.

**Comment by systemhalted** [comment]
@fleipold Were you able to release the latest version to Maven Central?
