### ISSUE TITLE
Bug in console output when using jproc to work with gpg

### ISSUE THREAD

**Issue by MichaelPetrenko** [fleipold/jproc#29]
Hello :)
I am using the latest 2.6.2 jproc release.
I am trying to execute command "gpg --import C://path/public.key" to import helm public key in java code using Jproc by this way:

`        ProcResult pr = new ProcBuilder("gpg").withArgs("--import", "C://path/public.key").run();
`
Command executing normally with exit code 0, but expected console output instead of being in "output" field of ProcResult object, located in "err" field as byte stream.
When I using `pr.getErrorString()` to see it, I see normal console output : "gpg: key C17701F951693F1F: public key imported".
I'm sure the console output gets there by mistake.
Thank you!

![1](https://user-images.githubusercontent.com/56554987/149381485-5ee21f93-5fe6-4902-9354-2083e2526fa7.png)
![2](https://user-images.githubusercontent.com/56554987/149380654-37c9628f-241c-4ef7-90d4-0b54ed045b58.png)
![3](https://user-images.githubusercontent.com/56554987/149380647-c0455a67-dae3-4e40-b0d6-9d6d3019cc44.png)

**Comment by fleipold** [comment]
@MichaelPetrenko thank you for using jproc and filing this report.

`gpg` is one of the tools that writes output that is informing the user about what happened / the progress of the operation to `stderr`. This is done so that the information to the user can be separated from the actual output of the program. An example where this makes sense is `gpg --export "donald.duck@xyz.com" > donald.key"`. Here only the actual key is written to the file and warnings etc. are written to the terminal.

Upshot: The output is actually written to `stderr` so the behaviour is as expected.

**Comment by MichaelPetrenko** [comment]
@fleipold 
Thank you for your response 👍
